services:
  app:
    build: .
    container_name: spring-webflux-app
    ports:
      - 8081:8080   # Puerto host:contenedor
    environment:
      - DB_URI=mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
      - DB_NAME=mydatabase
      - SERVER_PORT=8080
    depends_on:
      - mongodb
    volumes:
      - ./target:/app/target   # Mantener jar actualizado para desarrollo

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
