services:
  app:
    build: .
    container_name: spring-webflux-app
    ports:
      - 8081:8080
    environment:
      - DB_URI=mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
      - DB_NAME=mydatabase
      - SERVER_PORT=8080
    depends_on:
      - mongodb
    networks:
      - franquify-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - franquify-network

volumes:
  mongo-data:

networks:
  franquify-network:
    driver: bridge